"""baseline schema

Revision ID: 47f211f7faa8
Revises: 
Create Date: 2026-06-16 23:47:30.892116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f211f7faa8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('skill_name', sa.String(length=64), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_alerts_skill_name'), ['skill_name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('picture_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('api_calls_today', sa.Integer(), nullable=False),
    sa.Column('api_calls_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('alert_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=True),
    sa.Column('stock_id', sa.String(length=20), nullable=True),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('ai_context', sa.Text(), nullable=True),
    sa.Column('channels_sent', sa.String(length=100), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.create_index('ix_alert_history_date', ['delivered_at'], unique=False)
        batch_op.create_index('ix_alert_history_user', ['user_id'], unique=False)

    op.create_table('alert_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('channels', sa.String(length=100), nullable=False),
    sa.Column('enabled_categories', sa.Text(), nullable=False),
    sa.Column('quiet_start', sa.String(length=5), nullable=False),
    sa.Column('quiet_end', sa.String(length=5), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('morning_digest', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('alert_preferences', schema=None) as batch_op:
        batch_op.create_index('ix_alert_prefs_user', ['user_id'], unique=True)

    op.create_table('alert_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('stock_id', sa.String(length=20), nullable=True),
    sa.Column('condition_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.create_index('ix_alert_rules_active', ['user_id', 'is_active'], unique=False)
        batch_op.create_index('ix_alert_rules_stock', ['stock_id'], unique=False)
        batch_op.create_index('ix_alert_rules_user', ['user_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('stock_id', sa.String(length=20), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('ix_alert_active', ['user_id', 'is_active'], unique=False)
        batch_op.create_index('ix_alert_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('channel_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('channel_user_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('subscriptions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel', 'channel_user_id', name='uq_channel_user')
    )
    with op.batch_alter_table('channel_accounts', schema=None) as batch_op:
        batch_op.create_index('ix_channel_account_user', ['user_id'], unique=False)

    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('last_message_preview', sa.String(length=200), nullable=True),
    sa.Column('handoff_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_session_user', ['user_id'], unique=False)

    op.create_table('conversation_turns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.create_index('ix_conv_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_conv_user_session', ['user_id', 'session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_turns_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_turns_user_id'), ['user_id'], unique=False)

    op.create_table('feedback_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('turn_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('skill_name', sa.String(length=64), nullable=True),
    sa.Column('rating', sa.String(length=10), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_events_skill_name'), ['skill_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_events_turn_id'), ['turn_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_events_user_id'), ['user_id'], unique=False)

    op.create_table('llm_traces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('turn_id', sa.String(length=36), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_creation_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('time_to_first_token_ms', sa.Integer(), nullable=True),
    sa.Column('stop_reason', sa.String(length=30), nullable=True),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('system_prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_traces', schema=None) as batch_op:
        batch_op.create_index('ix_llm_traces_model', ['model'], unique=False)
        batch_op.create_index('ix_llm_traces_session', ['session_id'], unique=False)
        batch_op.create_index('ix_llm_traces_user_ts', ['user_id', 'created_at'], unique=False)

    op.create_table('oauth_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.String(length=2000), nullable=True),
    sa.Column('refresh_token', sa.String(length=2000), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_oauth_provider_user')
    )
    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_accounts_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_oauth_provider_user', ['provider', 'provider_user_id'], unique=False)

    op.create_table('portfolios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.create_index('ix_portfolio_user', ['user_id'], unique=False)

    op.create_table('semantic_facts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('fact_type', sa.String(length=50), nullable=False),
    sa.Column('fact_key', sa.String(length=200), nullable=False),
    sa.Column('fact_value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_session', sa.String(length=36), nullable=True),
    sa.Column('is_user_set', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('semantic_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_semantic_facts_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_semantic_user_key', ['user_id', 'fact_key'], unique=False)
        batch_op.create_index('ix_semantic_user_type', ['user_id', 'fact_type'], unique=False)

    op.create_table('tool_traces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('turn_id', sa.String(length=36), nullable=True),
    sa.Column('llm_trace_id', sa.String(length=36), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('args_summary', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_traces', schema=None) as batch_op:
        batch_op.create_index('ix_tool_traces_name', ['tool_name'], unique=False)
        batch_op.create_index('ix_tool_traces_turn', ['turn_id'], unique=False)
        batch_op.create_index('ix_tool_traces_user_ts', ['user_id', 'created_at'], unique=False)

    op.create_table('user_pet_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('total_pulls', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('last_login_date', sa.String(length=10), nullable=True),
    sa.Column('chat_count', sa.Integer(), nullable=False),
    sa.Column('available_pulls', sa.Integer(), nullable=False),
    sa.Column('pity_counter', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('user_pet_stats', schema=None) as batch_op:
        batch_op.create_index('ix_pet_stats_user', ['user_id'], unique=False)

    op.create_table('user_pets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('obtained_via', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_pets', schema=None) as batch_op:
        batch_op.create_index('ix_user_pet_active', ['user_id', 'is_active'], unique=False)
        batch_op.create_index('ix_user_pet_user', ['user_id'], unique=False)

    op.create_table('watchlists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.create_index('ix_watchlist_user', ['user_id'], unique=False)

    op.create_table('portfolio_holdings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('stock_id', sa.String(length=20), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('avg_cost', sa.Float(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_holdings', schema=None) as batch_op:
        batch_op.create_index('ix_holding_portfolio', ['portfolio_id'], unique=False)
        batch_op.create_index('ix_holding_stock', ['portfolio_id', 'stock_id'], unique=False)

    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('watchlist_id', sa.String(length=36), nullable=False),
    sa.Column('stock_id', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.create_index('ix_watchlist_item_list', ['watchlist_id'], unique=False)
        batch_op.create_index('ix_watchlist_item_stock', ['watchlist_id', 'stock_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.drop_index('ix_watchlist_item_stock')
        batch_op.drop_index('ix_watchlist_item_list')

    op.drop_table('watchlist_items')
    with op.batch_alter_table('portfolio_holdings', schema=None) as batch_op:
        batch_op.drop_index('ix_holding_stock')
        batch_op.drop_index('ix_holding_portfolio')

    op.drop_table('portfolio_holdings')
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.drop_index('ix_watchlist_user')

    op.drop_table('watchlists')
    with op.batch_alter_table('user_pets', schema=None) as batch_op:
        batch_op.drop_index('ix_user_pet_user')
        batch_op.drop_index('ix_user_pet_active')

    op.drop_table('user_pets')
    with op.batch_alter_table('user_pet_stats', schema=None) as batch_op:
        batch_op.drop_index('ix_pet_stats_user')

    op.drop_table('user_pet_stats')
    with op.batch_alter_table('tool_traces', schema=None) as batch_op:
        batch_op.drop_index('ix_tool_traces_user_ts')
        batch_op.drop_index('ix_tool_traces_turn')
        batch_op.drop_index('ix_tool_traces_name')

    op.drop_table('tool_traces')
    with op.batch_alter_table('semantic_facts', schema=None) as batch_op:
        batch_op.drop_index('ix_semantic_user_type')
        batch_op.drop_index('ix_semantic_user_key')
        batch_op.drop_index(batch_op.f('ix_semantic_facts_user_id'))

    op.drop_table('semantic_facts')
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_index('ix_portfolio_user')

    op.drop_table('portfolios')
    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.drop_index('ix_oauth_provider_user')
        batch_op.drop_index(batch_op.f('ix_oauth_accounts_user_id'))

    op.drop_table('oauth_accounts')
    with op.batch_alter_table('llm_traces', schema=None) as batch_op:
        batch_op.drop_index('ix_llm_traces_user_ts')
        batch_op.drop_index('ix_llm_traces_session')
        batch_op.drop_index('ix_llm_traces_model')

    op.drop_table('llm_traces')
    with op.batch_alter_table('feedback_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_events_turn_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_events_skill_name'))

    op.drop_table('feedback_events')
    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_turns_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_turns_session_id'))
        batch_op.drop_index('ix_conv_user_session')
        batch_op.drop_index('ix_conv_user_created')

    op.drop_table('conversation_turns')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_session_user')
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))

    op.drop_table('chat_sessions')
    with op.batch_alter_table('channel_accounts', schema=None) as batch_op:
        batch_op.drop_index('ix_channel_account_user')

    op.drop_table('channel_accounts')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_user_id'))
        batch_op.drop_index('ix_alert_user')
        batch_op.drop_index('ix_alert_active')

    op.drop_table('alerts')
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.drop_index('ix_alert_rules_user')
        batch_op.drop_index('ix_alert_rules_stock')
        batch_op.drop_index('ix_alert_rules_active')

    op.drop_table('alert_rules')
    with op.batch_alter_table('alert_preferences', schema=None) as batch_op:
        batch_op.drop_index('ix_alert_prefs_user')

    op.drop_table('alert_preferences')
    with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.drop_index('ix_alert_history_user')
        batch_op.drop_index('ix_alert_history_date')

    op.drop_table('alert_history')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('feedback_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_alerts_skill_name'))

    op.drop_table('feedback_alerts')
    # ### end Alembic commands ###
