from typing import Any

class Ticker:
    def __init__(self, ticker: str) -> None: ...
    @property
    def info(self) -> dict[str, Any]: ...
    @property
    def history_metadata(self) -> dict[str, Any]: ...
    @property
    def dividends(self) -> Any: ...
    @property
    def splits(self) -> Any: ...
    @property
    def actions(self) -> Any: ...
    @property
    def capital_gains(self) -> Any: ...
    @property
    def shares(self) -> Any: ...
    @property
    def income_stmt(self) -> Any: ...
    @property
    def quarterly_income_stmt(self) -> Any: ...
    @property
    def balance_sheet(self) -> Any: ...
    @property
    def quarterly_balance_sheet(self) -> Any: ...
    @property
    def cashflow(self) -> Any: ...
    @property
    def quarterly_cashflow(self) -> Any: ...
    @property
    def recommendations(self) -> Any: ...
    @property
    def recommendations_summary(self) -> Any: ...
    @property
    def sustainability(self) -> Any: ...
    @property
    def major_holders(self) -> Any: ...
    @property
    def institutional_holders(self) -> Any: ...
    @property
    def mutualfund_holders(self) -> Any: ...
    @property
    def insider_transactions(self) -> Any: ...
    @property
    def insider_purchases(self) -> Any: ...
    @property
    def insider_roster_holders(self) -> Any: ...
    @property
    def earnings(self) -> Any: ...
    @property
    def earnings_history(self) -> Any: ...
    @property
    def earnings_dates(self) -> Any: ...
    @property
    def eps_revisions(self) -> Any: ...
    @property
    def growth_estimates(self) -> Any: ...
    @property
    def analyst_price_targets(self) -> Any: ...
    @property
    def revenue_estimate(self) -> Any: ...
    @property
    def earnings_estimate(self) -> Any: ...
    @property
    def news(self) -> list[dict[str, Any]]: ...
    @property
    def calendar(self) -> dict[str, Any]: ...
    @property
    def isin(self) -> str: ...
    @property
    def options(self) -> tuple[str, ...]: ...
    @property
    def option_chain(self) -> Any: ...
    @property
    def fast_info(self) -> Any: ...
    @property
    def funds_data(self) -> Any: ...
    @property
    def sec_filings(self) -> Any: ...
    def history(self, **kwargs: Any) -> Any: ...
    def get_shares_full(self, **kwargs: Any) -> Any: ...

class Tickers:
    def __init__(self, tickers: str) -> None: ...

class Search:
    def __init__(self, query: str, **kwargs: Any) -> None: ...
    @property
    def quotes(self) -> list[dict[str, Any]]: ...
    @property
    def news(self) -> list[dict[str, Any]]: ...

class Sector:
    def __init__(self, key: str) -> None: ...
    @property
    def overview(self) -> dict[str, Any]: ...
    @property
    def top_companies(self) -> Any: ...

class Industry:
    def __init__(self, key: str) -> None: ...
    @property
    def overview(self) -> dict[str, Any]: ...
    @property
    def top_companies(self) -> Any: ...

class Market:
    def __init__(self, market: str) -> None: ...
    @property
    def summary(self) -> dict[str, Any]: ...

class EquityQuery:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class ETFQuery:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class FundQuery:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class Lookup:
    def __init__(self, query: str, asset_type: str = ..., **kwargs: Any) -> None: ...

class Calendars:
    def __init__(self) -> None: ...

def download(*args: Any, **kwargs: Any) -> Any: ...
def screen(*args: Any, **kwargs: Any) -> Any: ...

PREDEFINED_SCREENER_QUERIES: dict[str, Any]
