import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/constants";

/** /robots.txt — allow crawling public pages, disallow the authenticated app and
 *  API proxy, and point crawlers at the sitemap. Generated by Next.js. */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: "/",
      disallow: ["/dashboard/", "/api/", "/callback"],
    },
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
